# Generated by Django 5.2.7 on 2026-03-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='street_address',
            new_name='address',
        ),
    ]
