# Generated by Django 5.2.7 on 2026-03-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_uid_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default='TEMP', editable=False, max_length=20, unique=True),
        ),
    ]
