# Generated by Django 5.2.7 on 2026-03-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_cat_id_product_product_id_review_review_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.CharField(default='TEMP', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='TEMP', editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_id',
            field=models.CharField(default='TEMP', editable=False, max_length=25, unique=True),
        ),
    ]
