# Generated by Django 5.2.7 on 2025-10-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_email_buyerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyerprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="buyerprofile",
            name="phone",
            field=models.CharField(default=88888888888, max_length=15),
            preserve_default=False,
        ),
    ]
