# Generated by Django 5.2.7 on 2026-03-26 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_order_id_alter_orderitem_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_id',
            field=models.CharField(editable=False, max_length=25, unique=True),
        ),
    ]
