# Generated by Django 5.2.7 on 2025-10-18 06:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="images",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.URLField(), blank=True, null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
    ]
